VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "PBJoinForm"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public LinkID          As String
Public CorpNum         As String
Public CEOName         As String
Public CorpName        As String
Public Addr            As String
Public ZipCode         As String
Public BizType         As String
Public BizClass        As String
Public ID              As String
Public PWD             As String
Public ContactName     As String
Public ContactTEL      As String
Public ContactHP       As String
Public ContactFAX      As String
Public ContactEmail    As String

